icub3d_Evoker_Devastation_Spells = {
   -- Top Left -- 
   icub3d_Spell('Living Flame'),
   icub3d_Spell('Azure Strike'),
   icub3d_Spell('Pyre'),
   icub3d_Spell('Disintegrate'),
   icub3d_Spell('Fire Breath'),
   icub3d_Spell('Eternity Surge'),
   icub3d_Spell('Firestorm'),
   icub3d_Spell('Dream Flight'),
   icub3d_Spell('Shattering Star'),
   icub3d_Spell('Quell'),
   icub3d_Spell('Emerald Blossom'),
   icub3d_Spell('Verdant Embrace'),
   
   -- Top Right -- 
   icub3d_Spell('Dragonrage'),
   icub3d_Spell('Rescue'),
   icub3d_Spell('Deep Breath'),
   icub3d_Spell('Landslide'),
   icub3d_Spell('Sleep Walk'),
   icub3d_Spell('Emerald Communion'),
   icub3d_Spell('Time Dilation'),
   icub3d_Spell('Oppressing Roar'),
   icub3d_Spell('Zephyr'),
   icub3d_Spell('Glide'),
   icub3d_Spell('Time Spiral'),
   icub3d_Spell('Obsidian Scales'),

   -- Bottom Left --
   icub3d_Spell('Hover'),
   icub3d_Spell('Soar'),
   icub3d_Spell('Wing Buffet'),
   icub3d_Spell('Tail Swipe'),
   icub3d_Spell('Expunge'),
   icub3d_Spell('Cauterizing Flame'),
   icub3d_Spell('Unravel'),
   icub3d_Spell('Source of Magic'),
   icub3d_Spell('Tip the Scales'),
   icub3d_Spell('Renewing Blaze'),
   icub3d_Spell('Fury of the Aspects'),
   icub3d_Spell('Stasis'),
   
   -- Bottom Right --
   icub3d_Spell('Temporal Anomaly'),
   icub3d_Talent(1),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Macro('im_trinket'),
   icub3d_Macro('im_healthstone'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('Living Flame'),
   icub3d_Spell('Surge Forward(Racial)'),
   icub3d_Spell('Skyward Ascent(Racial)'),
   icub3d_Spell('Disintegrate'),
   icub3d_Spell('Fire Breath'),
   icub3d_Spell('Eternity Surge'),
   icub3d_Spell('Firestorm'),
   icub3d_Spell('Dream Flight'),
   icub3d_Spell('Shattering Star', 'Echo'),
   icub3d_Spell('Quell'),
   icub3d_Spell('Emerald Blossom'),
   icub3d_Spell('Verdant Embrace'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),


   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('Whirling Surge(Dragonriding)'),
   icub3d_Spell('Surge Forward(Dragonriding)'),
   icub3d_Spell('Skyward Ascent(Dragonriding)'),
   icub3d_Spell('Bronze Timelock(Dragonriding)'),
   icub3d_Spell('Living Flame'),
   icub3d_Spell('Azure Strike'),
   icub3d_Spell('Pyre'),
   icub3d_Spell('Disintegrate'),
   icub3d_Spell('Shattering Star', 'Echo'),
   icub3d_Spell('Quell'),
   icub3d_Spell('Emerald Blossom'),
   icub3d_Spell('Verdant Embrace'),
}

icub3d_Evoker_Preservation_Spells = {
   -- Top Left -- 
   icub3d_Spell('Living Flame'),
   icub3d_Spell('Temporal Anomaly'),
   icub3d_Spell('Reversion'),
   icub3d_Spell('Disintegrate'),
   icub3d_Spell('Dream Breath'),
   icub3d_Spell('Spiritbloom'),
   icub3d_Spell('Emerald Blossom'),
   icub3d_Spell('Dream Flight'),
   icub3d_Spell('Echo'),
   icub3d_Spell('Quell'),
   icub3d_Spell('Verdant Embrace'),
   icub3d_Spell('Fire Breath'),
   
   -- Top Right -- 
   icub3d_Spell('Rewind'),
   icub3d_Spell('Rescue'),
   icub3d_Spell('Deep Breath'),
   icub3d_Spell('Landslide'),
   icub3d_Spell('Sleep Walk'),
   icub3d_Spell('Emerald Communion'),
   icub3d_Spell('Time Dilation'),
   icub3d_Spell('Oppressing Roar'),
   icub3d_Spell('Zephyr'),
   icub3d_Spell('Glide'),
   icub3d_Spell('Time Spiral'),
   icub3d_Spell('Obsidian Scales'),

   -- Bottom Left --
   icub3d_Spell('Hover'),
   icub3d_Spell('Soar'),
   icub3d_Spell('Wing Buffet'),
   icub3d_Spell('Tail Swipe'),
   icub3d_Spell('Expunge'),
   icub3d_Spell('Cauterizing Flame'),
   icub3d_Spell('Unravel'),
   icub3d_Spell('Source of Magic'),
   icub3d_Spell('Tip the Scales'),
   icub3d_Spell('Renewing Blaze'),
   icub3d_Spell('Fury of the Aspects'),
   icub3d_Spell('Stasis'),
   
   -- Bottom Right --
   icub3d_Spell('Azure Strike'),
   icub3d_Talent(1),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Macro('im_trinket'),
   icub3d_Macro('im_healthstone'),
   icub3d_Skip(),
   icub3d_Spell('Blessing of the Bronze'),
   icub3d_Spell('Visage'),
   icub3d_Spell('Chosen Identity'),
   icub3d_Spell('Return'),
   icub3d_Spell('Mass Return'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('Living Flame'),
   icub3d_Spell('Azure Strike'),
   icub3d_Spell('Reversion'),
   icub3d_Spell('Disintegrate'),
   icub3d_Spell('Fire Breath'),
   icub3d_Spell('Spiritbloom'),
   icub3d_Spell('Dream Breath'),
   icub3d_Spell('Dream Flight'),
   icub3d_Spell('Echo'),
   icub3d_Spell('Quell'),
   icub3d_Spell('Emerald Blossom'),
   icub3d_Spell('Verdant Embrace'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('Whirling Surge(Dragonriding)'),
   icub3d_Spell('Surge Forward(Dragonriding)'),
   icub3d_Spell('Skyward Ascent(Dragonriding)'),
   icub3d_Spell('Bronze Timelock(Dragonriding)'),
   icub3d_Spell('Reversion'),
   icub3d_Spell('Spiritbloom'),
   icub3d_Spell('Dream Breath'),
   icub3d_Spell('Dream Flight'),
   icub3d_Spell('Echo'),
   icub3d_Spell('Quell'),
   icub3d_Spell('Emerald Blossom'),
   icub3d_Spell('Verdant Embrace'),
}


icub3d_Evoker_Talents = {
    -- PvP --
    icub3d_Spell('Chrono Loop'),
    icub3d_Spell('Nullifying Shroud'),
    icub3d_Spell('Time Stop'),
    icub3d_Spell('Swoop Up'),
 }

 icub3d_Spells['EVOKER'] = {
   specs = {
       {
          tags = {'d', 'devastation'},
          talent = icub3d_Evoker_Talents,
          actionbar = icub3d_Evoker_Devastation_Spells,
       },
       {
          tags = {'p', 'preservation'},
          talent = icub3d_Evoker_Talents,
          actionbar = icub3d_Evoker_Preservation_Spells,
       }
   }
 }