icub3d_Druid_Spells = {
   -- Normal Form
   icub3d_Spell('harm', 'Starfire', 'help', 'Rejuvenation', 'skip', 'skip'),
   icub3d_Spell('harm', 'Wrath', 'skip', 'skip'),
   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
   icub3d_Spell('help', 'Swiftmend', 'skip', 'skip'),
   icub3d_Spell('help', 'Wild Growth', 'skip', 'skip'),
   icub3d_Spell('help', 'Lifebloom', 'skip', 'skip'),
   icub3d_Spell('help', 'Efflorescence', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Spell('mouse', 'Ursol\'s Vortex', 'skip', 'skip'),
   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
   icub3d_Spell('help', 'Tranquility', 'skip', 'skip'),
   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
   

   -- Top Right
   icub3d_Spell('harm', 'Moonfire', 'skip', 'skip'),
   icub3d_Spell('help', 'Nature\'s Cure', 'help', 'Remove Corruption', 'skip', 'skip'),
   icub3d_Spell('help', 'Typhoon', 'skip', 'skip'),
   icub3d_Spell('harm', 'Cyclone', 'skip', 'skip'),
   icub3d_Talent(1),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Talent(4),
   icub3d_Talent(5),
   icub3d_Talent(6),
   icub3d_Talent(7),
   icub3d_Talent(8),
   
   -- Bottom Left
   icub3d_Spell('help', 'Dash'),
   icub3d_Spell('help', 'Prowl'),
   icub3d_Spell('help', 'Rebirth'),
   icub3d_Macro('im_cloak'),
   icub3d_Macro('im_racial'),
   icub3d_Spell('help', 'Gladiator\'s Medallion'),
   icub3d_Spell('harm', 'Entangling Roots'),
   icub3d_Spell('harm', 'Hibernate'),
   icub3d_Spell('harm', 'Soothe'),
   icub3d_Spell('help', 'Barkskin'),
   icub3d_Spell('help', 'Survival Instincts', 'skip', 'skip'),
   icub3d_Spell('simple', 'Bear Form'),

   -- Bottom Right
   icub3d_Spell('simple', 'Cat Form'),
   icub3d_Macro('im_travel'),
   icub3d_Spell('simple', 'Moonkin Form', 'macro', 'im_travel'),
   icub3d_Macro('im_belt'),
   icub3d_Macro('im_trinket'),
   icub3d_Spell("use", "Healthstone"),
   icub3d_Spell("use", "Battle Potion of Intellect"),
   icub3d_Spell("use", "Loot-A-Rang"),
   icub3d_Spell('simple', 'Revitalize', 'simple', 'Revive'),
   icub3d_Spell('simple', 'Revive'),
   icub3d_Spell('simple', 'Charm Woodland Creature'),
   icub3d_Spell('simple', 'Flap'),

   -- We have to skip these for druid, warrior, rogue
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   
   -- Cat Form
   icub3d_Spell('harm', 'Shred'),
   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
   icub3d_Spell('harm', 'Skull Bash', 'skip', 'skip'),
   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
   
   -- Prowl Form
   icub3d_Spell('harm', 'Shred'),
   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
   icub3d_Spell('harm', 'Skull Bash', 'skip', 'skip'),
   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

   -- Bear Form
   icub3d_Spell('harm', 'Mangle'),
   icub3d_Spell('harm', 'Maul', 'skip', 'skip'),
   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
   icub3d_Spell('help', 'Ironfur', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Spell('help', 'Frenzied Regeneration', 'skip', 'skip'),
   icub3d_Spell('harm', 'Incapacitating Roar', 'skip', 'skip'),
   icub3d_Spell('harm', 'Growl', 'skip', 'skip'),
   icub3d_Spell('harm', 'Skull Bash', 'skip', 'skip'),
   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

   -- Moonkin Form
   icub3d_Spell('harm', 'Starfire', 'skip', 'skip'),
   icub3d_Spell('harm', 'Wrath', 'skip', 'skip'),
   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
   icub3d_Spell('harm', 'Starfall', 'skip', 'skip'),
   icub3d_Spell('harm', 'Starsurge', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
   icub3d_Spell('help', 'Celestial Alignment', 'skip', 'skip'),
   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
}

icub3d_Spells['DRUID'] = {
    specs = {
        {
            tags = {'b', 'bal', 'balance'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Faerie Swarm'),
                    icub3d_Spell('harm', 'Cyclone'),
                    icub3d_Spell('help', 'Thorns')
                }
            },
            actionbar = {
			   -- Normal Form
			   icub3d_Spell('help', 'Rejuvenation', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Solar Wrath', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
			   icub3d_Spell('help', 'Swiftmend', 'skip', 'skip'),
			   icub3d_Spell('help', 'Wild Growth', 'skip', 'skip'),
			   icub3d_Spell('help', 'Lifebloom', 'skip', 'skip'),
			   icub3d_Spell('help', 'Efflorescence', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('mouse', 'Ursol\'s Vortex', 'skip', 'skip'),
			   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tranquility', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
			   

			   -- Top Right
			   icub3d_Spell('harm', 'Moonfire', 'skip', 'skip'),
			   icub3d_Spell('help', 'Nature\'s Cure', 'help', 'Remove Corruption', 'skip', 'skip'),
			   icub3d_Spell('both', 'Heart Essence', 'skip', 'skip'),
			   icub3d_Spell('mouse', 'Solar Beam', 'harm', 'Skull Bash', 'skip', 'skip'),
			   icub3d_Spell('mouse', 'Force of Nature', 'help', 'Warrior of Elune', 'skip', 'skip'),
			   icub3d_Spell('both', 'Wild Charge', 'help', 'Renewal', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Mighty Bash', 'harm', 'Mass Entanglement', 'help', 'Heart of the Wild', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Stellar Flare', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Fury of Elune', 'skip', 'skip'),
			   icub3d_PvPTalent(1),
			   icub3d_PvPTalent(2),
			   icub3d_PvPTalent(3),
			   
			   -- Bottom Left
			   icub3d_Spell('help', 'Dash'),
			   icub3d_Spell('help', 'Prowl'),
			   icub3d_Spell('help', 'Rebirth'),
			   icub3d_Macro('im_cloak'),
			   icub3d_Macro('im_racial'),
			   icub3d_Spell('help', 'Gladiator\'s Medallion'),
			   icub3d_Spell('harm', 'Entangling Roots'),
			   icub3d_Spell('harm', 'Hibernate'),
			   icub3d_Spell('harm', 'Soothe'),
			   icub3d_Spell('help', 'Barkskin'),
			   icub3d_Spell('help', 'Survival Instincts', 'skip', 'skip'),
			   icub3d_Spell('simple', 'Bear Form'),

			   -- Bottom Right
			   icub3d_Spell('simple', 'Cat Form'),
			   icub3d_Macro('im_travel'),
			   icub3d_Spell('simple', 'Moonkin Form', 'macro', 'im_travel'),
			   icub3d_Macro('im_belt'),
			   icub3d_Macro('im_trinket'),
			   icub3d_Spell("use", "Healthstone"),
			   icub3d_Spell("use", "Battle Potion of Intellect"),
			   icub3d_Spell("use", "Loot-A-Rang"),
			   icub3d_Spell('simple', 'Revitalize'),
			   icub3d_Spell('simple', 'Revive'),
			   icub3d_Spell('simple', 'Charm Woodland Creature'),
			   icub3d_Spell('simple', 'Flap'),

			   -- We have to skip these for druid, warrior, rogue
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   
			   -- Cat Form
			   icub3d_Spell('harm', 'Shred'),
			   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
			   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
			   
			   -- Prowl Form
			   icub3d_Spell('harm', 'Shred'),
			   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
			   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

			   -- Bear Form
			   icub3d_Spell('harm', 'Mangle'),
			   icub3d_Spell('harm', 'Maul', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('help', 'Ironfur', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Frenzied Regeneration', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Incapacitating Roar', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Growl', 'skip', 'skip'),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

			   -- Moonkin Form
			   icub3d_Spell('harm', 'Lunar Strike', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Solar Wrath', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Starfall', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Starsurge', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
			   icub3d_Spell('help', 'Celestial Alignment', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
            }
        },
        {
            tags = {'f', 'feral'},
			talents = {
			   ['general'] = {2, 3, 1, 1, 1, 2, 2}
			},
			talent = {
			   icub3d_Spell('both', 'Wild Charge'),
			   icub3d_Spell('help', 'Renewal'),
			   icub3d_Spell('harm', 'Mighty Bash'),
			   icub3d_Spell('harm', 'Mass Entanglement'),
			   icub3d_Spell('help', 'Heart of the Wild'),
			   icub3d_Spell('help', 'Savage Roar'),
			   icub3d_Spell('harm', 'Primal Wrath'),
			   icub3d_Spell('harm', 'Feral Frenzy'),
			   icub3d_Spell('help', 'Thorns'),
			   icub3d_Spell('harm', 'Rip and Tear'),
			},
            actionbar = icub3d_Druid_Spells,
        },
        {
            tags = {'g', 'guard', 'guardian'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Demoralizing Roar'),
                    icub3d_Spell('harm', 'Overrun')
                }
            },
            actionbar = {
			   -- Normal Form
			   icub3d_Spell('help', 'Rejuvenation', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Solar Wrath', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
			   icub3d_Spell('help', 'Swiftmend', 'skip', 'skip'),
			   icub3d_Spell('help', 'Wild Growth', 'skip', 'skip'),
			   icub3d_Spell('help', 'Lifebloom', 'skip', 'skip'),
			   icub3d_Spell('help', 'Efflorescence', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('mouse', 'Ursol\'s Vortex', 'skip', 'skip'),
			   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tranquility', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
			   

			   -- Top Right
			   icub3d_Spell('harm', 'Moonfire', 'skip', 'skip'),
			   icub3d_Spell('help', 'Nature\'s Cure', 'help', 'Remove Corruption', 'skip', 'skip'),
			   icub3d_Spell('both', 'Heart Essence', 'skip', 'skip'),
			   icub3d_Spell('mouse', 'Solar Beam', 'harm', 'Skull Bash', 'skip', 'skip'),
			   icub3d_Spell('help', 'Bristling Fur', 'skip', 'skip'),
			   icub3d_Spell('both', 'Wild Charge', 'mouse', 'Ursol\'s Vortex', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Mighty Bash', 'harm', 'Mass Entanglement', 'harm', 'Typhoon', 'skip', 'skip'),
			   icub3d_Spell('help', 'Incarnation: Guardian of Ursoc', 'skip', 'skip'),
			   icub3d_Spell('help', 'Lunar Beam', 'harm', 'Pulverize',  'skip', 'skip'),
			   icub3d_PvPTalent(1),
			   icub3d_PvPTalent(2),
			   icub3d_PvPTalent(3),
			   
			   -- Bottom Left
			   icub3d_Spell('help', 'Dash'),
			   icub3d_Spell('help', 'Prowl'),
			   icub3d_Spell('help', 'Rebirth'),
			   icub3d_Macro('im_cloak'),
			   icub3d_Macro('im_racial'),
			   icub3d_Spell('help', 'Gladiator\'s Medallion'),
			   icub3d_Spell('harm', 'Entangling Roots'),
			   icub3d_Spell('harm', 'Hibernate'),
			   icub3d_Spell('harm', 'Soothe'),
			   icub3d_Spell('help', 'Barkskin'),
			   icub3d_Spell('help', 'Survival Instincts', 'skip', 'skip'),
			   icub3d_Spell('simple', 'Bear Form'),

			   -- Bottom Right
			   icub3d_Spell('simple', 'Cat Form'),
			   icub3d_Macro('im_travel'),
			   icub3d_Spell('simple', 'Moonkin Form', 'macro', 'im_travel'),
			   icub3d_Macro('im_belt'),
			   icub3d_Macro('im_trinket'),
			   icub3d_Spell("use", "Healthstone"),
			   icub3d_Spell("use", "Battle Potion of Intellect"),
			   icub3d_Spell("use", "Loot-A-Rang"),
			   icub3d_Spell('simple', 'Revitalize'),
			   icub3d_Spell('simple', 'Revive'),
			   icub3d_Spell('simple', 'Charm Woodland Creature'),
			   icub3d_Spell('simple', 'Flap'),

			   -- We have to skip these for druid, warrior, rogue
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   
			   -- Cat Form
			   icub3d_Spell('harm', 'Shred'),
			   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
			   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
			   
			   -- Prowl Form
			   icub3d_Spell('harm', 'Shred'),
			   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
			   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

			   -- Bear Form
			   icub3d_Spell('harm', 'Mangle'),
			   icub3d_Spell('harm', 'Maul', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('help', 'Ironfur', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Frenzied Regeneration', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Incapacitating Roar', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Growl', 'skip', 'skip'),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

			   -- Moonkin Form
			   icub3d_Spell('harm', 'Lunar Strike', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Solar Wrath', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Starfall', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Starsurge', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
			   icub3d_Spell('help', 'Celestial Alignment', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
            }
        },
        {
            tags = {'r', 'resto', 'restoration'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Nourish'),
                    icub3d_Spell('harm', 'Cyclone'),
                    icub3d_Spell('help', 'Thorns'),
                    icub3d_Spell('help', 'Mark of the Wild'),
                    icub3d_Spell('help', 'Overgrowth')
                }
            },
            actionbar = {
			   -- Normal Form
			   icub3d_Spell('help', 'Rejuvenation', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Solar Wrath', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
			   icub3d_Spell('help', 'Swiftmend', 'skip', 'skip'),
			   icub3d_Spell('help', 'Wild Growth', 'skip', 'skip'),
			   icub3d_Spell('help', 'Lifebloom', 'skip', 'skip'),
			   icub3d_Spell('help', 'Efflorescence', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('mouse', 'Ursol\'s Vortex', 'skip', 'skip'),
			   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tranquility', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
			   

			   -- Top Right
			   icub3d_Spell('harm', 'Moonfire', 'skip', 'skip'),
			   icub3d_Spell('help', 'Nature\'s Cure', 'help', 'Remove Corruption', 'skip', 'skip'),
			   icub3d_Spell('both', 'Heart Essence', 'skip', 'skip'),
			   icub3d_Spell('mouse', 'Solar Beam', 'harm', 'Skull Bash', 'skip', 'skip'),
			   icub3d_Spell('help', 'Cenarion Ward', 'skip', 'skip'),
			   icub3d_Spell('both', 'Wild Charge', 'help', 'Renewal', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Mighty Bash', 'harm', 'Mass Entanglement', 'harm', 'Typhoon', 'skip', 'skip'),
			   icub3d_Spell('help', 'Incarnation: Tree of Life', 'skip', 'skip'),
			   icub3d_Spell('help', 'Flourish',  'skip', 'skip'),
			   icub3d_PvPTalent(1),
			   icub3d_PvPTalent(2),
			   icub3d_PvPTalent(3),
			   
			   -- Bottom Left
			   icub3d_Spell('help', 'Dash'),
			   icub3d_Spell('help', 'Prowl'),
			   icub3d_Spell('help', 'Rebirth'),
			   icub3d_Macro('im_cloak'),
			   icub3d_Macro('im_racial'),
			   icub3d_Spell('help', 'Gladiator\'s Medallion'),
			   icub3d_Spell('harm', 'Entangling Roots'),
			   icub3d_Spell('harm', 'Hibernate'),
			   icub3d_Spell('harm', 'Soothe'),
			   icub3d_Spell('help', 'Barkskin'),
			   icub3d_Spell('help', 'Survival Instincts', 'skip', 'skip'),
			   icub3d_Spell('simple', 'Bear Form'),

			   -- Bottom Right
			   icub3d_Spell('simple', 'Cat Form'),
			   icub3d_Macro('im_travel'),
			   icub3d_Spell('simple', 'Moonkin Form', 'macro', 'im_travel'),
			   icub3d_Macro('im_belt'),
			   icub3d_Macro('im_trinket'),
			   icub3d_Spell("use", "Healthstone"),
			   icub3d_Spell("use", "Battle Potion of Intellect"),
			   icub3d_Spell("use", "Loot-A-Rang"),
			   icub3d_Spell('simple', 'Revitalize'),
			   icub3d_Spell('simple', 'Revive'),
			   icub3d_Spell('simple', 'Charm Woodland Creature'),
			   icub3d_Spell('simple', 'Flap'),

			   -- We have to skip these for druid, warrior, rogue
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   
			   -- Cat Form
			   icub3d_Spell('harm', 'Shred'),
			   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
			   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
			   
			   -- Prowl Form
			   icub3d_Spell('harm', 'Shred'),
			   icub3d_Spell('harm', 'Rake', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Ferocious Bite', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Maim', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Rip', 'skip', 'skip'),
			   icub3d_Spell('help', 'Tiger\'s Fury', 'skip', 'skip'),
			   icub3d_Spell('help', 'Berserk', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

			   -- Bear Form
			   icub3d_Spell('harm', 'Mangle'),
			   icub3d_Spell('harm', 'Maul', 'skip', 'skip'),
			   icub3d_Spell('both', 'Thrash', 'skip', 'skip'),
			   icub3d_Spell('both', 'Swipe', 'skip', 'skip'),
			   icub3d_Spell('help', 'Ironfur', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Frenzied Regeneration', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Incapacitating Roar', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Growl', 'skip', 'skip'),
			   icub3d_Spell('help', 'Stampeding Roar', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),

			   -- Moonkin Form
			   icub3d_Spell('harm', 'Lunar Strike', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Solar Wrath', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Sunfire', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Starfall', 'skip', 'skip'),
			   icub3d_Spell('harm', 'Starsurge', 'skip', 'skip'),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Skip(),
			   icub3d_Spell('help', 'Innervate', 'skip', 'skip'),
			   icub3d_Spell('help', 'Celestial Alignment', 'skip', 'skip'),
			   icub3d_Spell('help', 'Regrowth', 'skip', 'skip'),
            }
        }
    }
}
