icub3d_DemonHunter_Spells = {
   -- Top --
   icub3d_Spell('harm', 'Shear', 'harm', 'Demon\'s Bite', 'skip', 'skip'),
   icub3d_Spell('harm', 'Soul Cleave', 'harm', 'Chaos Strike', 'skip', 'skip'),
   icub3d_Spell('harm', 'Throw Glaive', 'skip', 'skip'),
   icub3d_Spell('harm', 'Felblade', 'skip', 'skip'),
   icub3d_Spell('harm', 'Blade Dance', 'harm', 'Spirit Bomb', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Infernal Strike', 'harm', 'Fel Rush', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Sigil of Flame', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Sigil of Misery', 'skip', 'skip'),
   icub3d_Spell('harm', 'Eye Beam', 'harm', 'Fel Devastation', 'skip', 'skip'),
   icub3d_Spell('harm', 'Disrupt', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fel Eruption', 'harm', 'Fiery Brand', 'skip', 'skip'),
   icub3d_Spell('harm', 'Essence Break', 'skip', 'skip'),
   icub3d_Spell('harm', 'Vengeful Retreat', 'skip', 'skip'),
   icub3d_Spell('harm', 'Imprison', 'skip', 'skip'),
   icub3d_Spell('harm', 'Consume Magic', 'skip', 'skip'),
   icub3d_Spell('harm', 'The Hunt', 'skip', 'skip'),
   icub3d_Spell('harm', 'Chaos Nova', 'skip', 'skip'),
   icub3d_Spell('harm', 'Darkness', 'skip', 'skip'),
   icub3d_Spell('use', 'Goblin Glider Kit'),
   icub3d_Spell('harm', 'Spectral Sight', 'skip', 'skip'),
   icub3d_Skip(), -- POTS
   icub3d_Spell('help', 'Netherwalk', 'harm', 'Soul Carver', 'skip', 'skip'),
   icub3d_Spell('harm', 'Immolation Aura', 'skip', 'skip'),
   icub3d_Spell('harm', 'Metamorphosis', 'skip', 'skip'),

   -- Bottom --
   icub3d_Spell('help', 'Blur', 'help', 'Demon Spikes', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fel Barrage', 'harm', 'Glaive Tempest', 'harm', 'Bulk Extraction', 'harm', 'Soul Barrier', 'skip', 'skip'),
   icub3d_Macro('im_racial'),
   icub3d_Spell('mouse', 'Sigil of Silence', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Sigil of Chains', 'skip', 'skip'),
   icub3d_Talent(1),
   icub3d_Spell('mouse', 'Elysian Decree', 'skip', 'skip'),
   icub3d_Spell('harm', 'Torment'),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Macro('im_healthstone'),
   icub3d_Macro('im_trinket'),
   icub3d_Macro('im_cloak'),
   icub3d_Macro('im_belt'),
   icub3d_Spell('use', 'Soft Foam Sword'),
   icub3d_Spell('use', 'Loot-A-Rang'),
   icub3d_Spell('help', 'Glide'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('harm', 'Shear', 'harm', 'Demon\'s Bite', 'skip', 'skip'),
   icub3d_Spell('harm', 'Soul Cleave', 'harm', 'Chaos Strike', 'skip', 'skip'),
   icub3d_Spell('harm', 'Throw Glaive', 'skip', 'skip'),
   icub3d_Spell('harm', 'Felblade', 'skip', 'skip'),
   icub3d_Spell('harm', 'Blade Dance', 'harm', 'Spirit Bomb', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fel Rush', 'mouse', 'Infernal Strike', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Sigil of Flame', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Sigil of Misery', 'skip', 'skip'),
   icub3d_Spell('harm', 'Eye Beam', 'harm', 'Fel Devastation', 'skip', 'skip'),
   icub3d_Spell('harm', 'Disrupt', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fel Eruption', 'harm', 'Fiery Brand', 'skip', 'skip'),
   icub3d_Spell('harm', 'Essence Break', 'skip', 'skip'),

}

icub3d_DemonHunter_Talents = {
   -- PvP --
   icub3d_Spell('harm', 'Rain from Above'),
   icub3d_Spell('harm', 'Illidan\'s Grasp'),
   icub3d_Spell('harm', 'Reverse Magic'),
   icub3d_Spell('harm', 'Demonic Trample'),
}

icub3d_Spells['DEMONHUNTER'] = {
   specs = {
	  -- The tags are useful for switching but these should be in in-game order.
	  {
		 tags = {'h', 'havoc'},
		 talents = {
			['dungeon'] = {1, 1, 3, 3, 1, 3, 1},
			['felblade'] = {3, 3, 3, 3, 2, 3, 2},
			['demonic'] = {3, 3, 2, 1, 2, 3, 1},
			['momentum'] = {3, 3, 2, 3, 2, 3, 2},
		 },
		 talent = icub3d_DemonHunter_Talents,
		 actionbar = icub3d_DemonHunter_Spells,
	  },
	  {
		 tags = {'v', 'veng', 'vengeance'},
		 talents = {
			['quest'] = {1, 2, 1, 3, 2, 1, 1},
			['bomb'] = {1, 2, 3, 3, 3, 2, 1},
			['brand'] = {2, 3, 2, 3, 2, 2, 1},
			['control'] = {1, 3, 1, 3, 3, 2, 1},
		 },
		 talent = icub3d_DemonHunter_Talents,
		 actionbar = icub3d_DemonHunter_Spells,
	  }
   }
}
