icub3d_DemonHunter_Spells = {
   -- Top --
   icub3d_Spell('Shear', 'Demon\'s Bite'),
   icub3d_Spell('Soul Cleave', 'Chaos Strike'),
   icub3d_Spell('Throw Glaive'),
   icub3d_Spell('Felblade'),
   icub3d_Spell('Blade Dance', 'Spirit Bomb'),
   icub3d_Spell('Infernal Strike', 'Fel Rush'),
   icub3d_Spell('Sigil of Flame'),
   icub3d_Spell('Sigil of Misery'),
   icub3d_Spell('Eye Beam', 'Fel Devastation'),
   icub3d_Spell('Disrupt'),
   icub3d_Spell('Fel Eruption', 'Fiery Brand'),
   icub3d_Spell('Essence Break'),
   icub3d_Spell('Vengeful Retreat'),
   icub3d_Spell('Imprison'),
   icub3d_Spell('Consume Magic'),
   icub3d_Spell('The Hunt'),
   icub3d_Spell('Chaos Nova'),
   icub3d_Spell('Darkness'),
   icub3d_Spell('Goblin Glider Kit'),
   icub3d_Spell('Spectral Sight'),
   icub3d_Skip(), -- POTS
   icub3d_Spell('Netherwalk', 'Soul Carver'),
   icub3d_Spell('Immolation Aura'),
   icub3d_Spell('Metamorphosis'),

   -- Bottom --
   icub3d_Spell('Blur', 'Demon Spikes'),
   icub3d_Spell('Fel Barrage', 'Glaive Tempest', 'Bulk Extraction', 'Soul Barrier'),
   icub3d_Macro('im_racial'),
   icub3d_Spell('Sigil of Silence'),
   icub3d_Spell('Sigil of Chains'),
   icub3d_Talent(1),
   icub3d_Spell('Elysian Decree'),
   icub3d_Spell('Torment'),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Macro('im_healthstone'),
   icub3d_Macro('im_trinket'),
   icub3d_Macro('im_cloak'),
   icub3d_Macro('im_belt'),
   icub3d_Spell('Soft Foam Sword'),
   icub3d_Spell('Loot-A-Rang'),
   icub3d_Spell('Glide'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('Shear', 'Demon\'s Bite'),
   icub3d_Spell('Soul Cleave', 'Chaos Strike'),
   icub3d_Spell('Throw Glaive'),
   icub3d_Spell('Felblade'),
   icub3d_Spell('Blade Dance', 'Spirit Bomb'),
   icub3d_Spell('Fel Rush', 'Infernal Strike'),
   icub3d_Spell('Sigil of Flame'),
   icub3d_Spell('Sigil of Misery'),
   icub3d_Spell('Eye Beam', 'Fel Devastation'),
   icub3d_Spell('Disrupt'),
   icub3d_Spell('Fel Eruption', 'Fiery Brand'),
   icub3d_Spell('Essence Break'),

}

icub3d_DemonHunter_Talents = {
   -- PvP --
   icub3d_Spell('Rain from Above'),
   icub3d_Spell('Illidan\'s Grasp'),
   icub3d_Spell('Reverse Magic'),
   icub3d_Spell('Demonic Trample'),
}

icub3d_Spells['DEMONHUNTER'] = {
   specs = {
      -- The tags are useful for switching but these should be in in-game order.
      {
         tags = { 'h', 'havoc' },
         talents = {
            ['dungeon'] = { 1, 1, 3, 3, 1, 3, 1 },
            ['felblade'] = { 3, 3, 3, 3, 2, 3, 2 },
            ['demonic'] = { 3, 3, 2, 1, 2, 3, 1 },
            ['momentum'] = { 3, 3, 2, 3, 2, 3, 2 },
         },
         talent = icub3d_DemonHunter_Talents,
         actionbar = icub3d_DemonHunter_Spells,
      },
      {
         tags = { 'v', 'veng', 'vengeance' },
         talents = {
            ['quest'] = { 1, 2, 1, 3, 2, 1, 1 },
            ['bomb'] = { 1, 2, 3, 3, 3, 2, 1 },
            ['brand'] = { 2, 3, 2, 3, 2, 2, 1 },
            ['control'] = { 1, 3, 1, 3, 3, 2, 1 },
         },
         talent = icub3d_DemonHunter_Talents,
         actionbar = icub3d_DemonHunter_Spells,
      }
   }
}
