icub3d_Warrior_Spells = {
   -- Top Left -- 
   icub3d_Spell('Shield Slam'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('Shield Block'),
   icub3d_Spell('harm' , 'Taunt'),
   icub3d_Spell('Victory Rush'),
   icub3d_Skip(),
   icub3d_Spell('Devastate'),
   icub3d_Spell('Pummel'),
   icub3d_Skip(),
   icub3d_Skip(),
   
   -- Top Right -- 
   icub3d_Macro('im_warrior_stances'),
   icub3d_Spell('Execute'),
   icub3d_Spell('Whirlwind'),
   icub3d_Skip(),
   icub3d_Spell('Heroic Throw'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   -- Bottom Left --
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('Charge'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   
   -- Bottom Right --
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('Hamstring'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('Slam'),
   icub3d_Spell('Battle Shout'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   -- Druid and other forms --
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('Whirling Surge(Dragonriding)'),
   icub3d_Spell('Surge Forward(Dragonriding)'),
   icub3d_Spell('Skyward Ascent(Dragonriding)'),
   icub3d_Spell('Bronze Timelock(Dragonriding)'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
}

icub3d_Warrior_Talents = {
 }

 icub3d_Spells['WARRIOR'] = {
   specs = {
       {
          tags = {'a', 'arms'},
          talent = icub3d_Warrior_Talents,
          actionbar = icub3d_Warrior_Spells,
       },
       {
         tags = {'f', 'fury'},
         talent = icub3d_Warrior_Talents,
         actionbar = icub3d_Warrior_Spells,
      },
      {
         tags = {'p', 'prot', 'protection'},
         talent = icub3d_Warrior_Talents,
         actionbar = icub3d_Warrior_Spells,
      },
   }
 }