icub3d_Warrior_Spells = {
   -- Top Left -- 
   icub3d_Spell('harm', 'Shield Slam', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('help', 'Shield Block', 'skip', 'skip'),
   icub3d_Spell('harm' , 'Taunt', 'skip', 'skip'),
   icub3d_Spell('harm', 'Victory Rush', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Spell('harm', 'Devastate', 'skip', 'skip'),
   icub3d_Spell('harm', 'Pummel', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Skip(),
   
   -- Top Right -- 
   icub3d_Macro('im_warrior_stances'),
   icub3d_Spell('harm', 'Execute', 'skip', 'skip'),
   icub3d_Spell('harm', 'Whirlwind', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Spell('harm', 'Heroic Throw', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   -- Bottom Left --
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('harm', 'Charge', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   
   -- Bottom Right --
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('harm', 'Hamstring', 'skip', 'skip'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Spell('harm', 'Slam', 'skip', 'skip'),
   icub3d_Spell('help', 'Battle Shout'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   -- Druid and other forms --
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('simple', 'Whirling Surge(Dragonriding)'),
   icub3d_Spell('simple', 'Surge Forward(Dragonriding)'),
   icub3d_Spell('simple', 'Skyward Ascent(Dragonriding)'),
   icub3d_Spell('simple', 'Bronze Timelock(Dragonriding)'),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
}

icub3d_Warrior_Talents = {
 }

 icub3d_Spells['WARRIOR'] = {
   specs = {
       {
          tags = {'a', 'arms'},
          talent = icub3d_Warrior_Talents,
          actionbar = icub3d_Warrior_Spells,
       },
       {
         tags = {'f', 'fury'},
         talent = icub3d_Warrior_Talents,
         actionbar = icub3d_Warrior_Spells,
      },
      {
         tags = {'p', 'prot', 'protection'},
         talent = icub3d_Warrior_Talents,
         actionbar = icub3d_Warrior_Spells,
      },
   }
 }