icub3d_Evoker_Devastation_Spells = {
   -- Top Left -- 
   icub3d_Spell('both', 'Living Flame', 'skip', 'skip'),
   icub3d_Spell('harm', 'Azure Strike', 'skip', 'skip'),
   icub3d_Spell('harm', 'Pyre', 'skip', 'skip'),
   icub3d_Spell('harm', 'Disintegrate', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fire Breath', 'skip', 'skip'),
   icub3d_Spell('harm', 'Eternity Surge', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Firestorm', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Flight', 'skip', 'skip'),
   icub3d_Spell('harm', 'Shattering Star', 'skip', 'skip'),
   icub3d_Spell('harm', 'Quell', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Blossom', 'skip', 'skip'),
   icub3d_Spell('help', 'Verdant Embrace', 'skip', 'skip'),
   
   -- Top Right -- 
   icub3d_Spell('harm', 'Dragonrage', 'skip', 'skip'),
   icub3d_Spell('help', 'Rescue', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Deep Breath', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Landslide', 'skip', 'skip'),
   icub3d_Spell('harm', 'Sleep Walk', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Communion', 'skip', 'skip'),
   icub3d_Spell('help', 'Time Dilation', 'skip', 'skip'),
   icub3d_Spell('help', 'Oppressing Roar', 'skip', 'skip'),
   icub3d_Spell('help', 'Zephyr', 'skip', 'skip'),
   icub3d_Spell('help', 'Glide', 'skip', 'skip'),
   icub3d_Spell('help', 'Time Spiral', 'skip', 'skip'),
   icub3d_Spell('help', 'Obsidian Scales', 'skip', 'skip'),

   -- Bottom Left --
   icub3d_Spell('help', 'Hover', 'skip', 'skip'),
   icub3d_Spell('help', 'Soar', 'skip', 'skip'),
   icub3d_Spell('help', 'Wing Buffet', 'skip', 'skip'),
   icub3d_Spell('help', 'Tail Swipe', 'skip', 'skip'),
   icub3d_Spell('help', 'Expunge', 'skip', 'skip'),
   icub3d_Spell('help', 'Cauterizing Flame', 'skip', 'skip'),
   icub3d_Spell('help', 'Unravel', 'skip', 'skip'),
   icub3d_Spell('help', 'Source of Magic', 'skip', 'skip'),
   icub3d_Spell('help', 'Tip the Scales', 'skip', 'skip'),
   icub3d_Spell('help', 'Renewing Blaze', 'skip', 'skip'),
   icub3d_Spell('help', 'Fury of the Aspects', 'skip', 'skip'),
   icub3d_Spell('help', 'Stasis', 'skip', 'skip'),
   
   -- Bottom Right --
   icub3d_Spell('help', 'Temporal Anomaly', 'skip', 'skip'),
   icub3d_Talent(1),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Macro('im_trinket'),
   icub3d_Macro('im_healthstone'),
   icub3d_Skip(),
   icub3d_Spell('help', 'Blessing of the Bronze', 'skip', 'skip'),
   icub3d_Spell('help', 'Visage', 'skip', 'skip'),
   icub3d_Spell('help', 'Chosen Identity', 'skip', 'skip'),
   icub3d_Spell('help', 'Return', 'skip', 'skip'),
   icub3d_Spell('help', 'Mass Return', 'skip', 'skip'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('both', 'Living Flame', 'skip', 'skip'),
   icub3d_Spell('simple', 'Surge Forward'),
   icub3d_Spell('simple', 'Skyward Ascent'),
   icub3d_Spell('harm', 'Disintegrate', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fire Breath', 'skip', 'skip'),
   icub3d_Spell('harm', 'Eternity Surge', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Firestorm', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Flight', 'skip', 'skip'),
   icub3d_Spell('harm', 'Shattering Star', 'mouse', 'Echo', 'skip', 'skip'),
   icub3d_Spell('harm', 'Quell', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Blossom', 'skip', 'skip'),
   icub3d_Spell('help', 'Verdant Embrace', 'skip', 'skip'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('simple', 'Whirling Surge(Dragonriding)'),
   icub3d_Spell('simple', 'Surge Forward(Dragonriding)'),
   icub3d_Spell('simple', 'Skyward Ascent(Dragonriding)'),
   icub3d_Spell('simple', 'Bronze Timelock(Dragonriding)'),
   icub3d_Spell('both', 'Living Flame', 'skip', 'skip'),
   icub3d_Spell('harm', 'Azure Strike', 'skip', 'skip'),
   icub3d_Spell('harm', 'Pyre', 'skip', 'skip'),
   icub3d_Spell('harm', 'Disintegrate', 'skip', 'skip'),
   icub3d_Spell('harm', 'Shattering Star', 'mouse', 'Echo', 'skip', 'skip'),
   icub3d_Spell('harm', 'Quell', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Blossom', 'skip', 'skip'),
   icub3d_Spell('help', 'Verdant Embrace', 'skip', 'skip'),
}

icub3d_Evoker_Preservation_Spells = {
   -- Top Left -- 
   icub3d_Spell('both', 'Living Flame', 'skip', 'skip'),
   icub3d_Spell('harm', 'Azure Strike', 'skip', 'skip'),
   icub3d_Spell('help', 'Reversion', 'skip', 'skip'),
   icub3d_Spell('harm', 'Disintegrate', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fire Breath', 'skip', 'skip'),
   icub3d_Spell('help', 'Spiritbloom', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Breath', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Flight', 'skip', 'skip'),
   icub3d_Spell('help', 'Echo', 'skip', 'skip'),
   icub3d_Spell('harm', 'Quell', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Blossom', 'skip', 'skip'),
   icub3d_Spell('help', 'Verdant Embrace', 'skip', 'skip'),
   
   -- Top Right -- 
   icub3d_Spell('help', 'Rewind', 'skip', 'skip'),
   icub3d_Spell('help', 'Rescue', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Deep Breath', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Landslide', 'skip', 'skip'),
   icub3d_Spell('harm', 'Sleep Walk', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Communion', 'skip', 'skip'),
   icub3d_Spell('help', 'Time Dilation', 'skip', 'skip'),
   icub3d_Spell('help', 'Oppressing Roar', 'skip', 'skip'),
   icub3d_Spell('help', 'Zephyr', 'skip', 'skip'),
   icub3d_Spell('help', 'Glide', 'skip', 'skip'),
   icub3d_Spell('help', 'Time Spiral', 'skip', 'skip'),
   icub3d_Spell('help', 'Obsidian Scales', 'skip', 'skip'),

   -- Bottom Left --
   icub3d_Spell('help', 'Hover', 'skip', 'skip'),
   icub3d_Spell('help', 'Soar', 'skip', 'skip'),
   icub3d_Spell('help', 'Wing Buffet', 'skip', 'skip'),
   icub3d_Spell('help', 'Tail Swipe', 'skip', 'skip'),
   icub3d_Spell('help', 'Expunge', 'skip', 'skip'),
   icub3d_Spell('help', 'Cauterizing Flame', 'skip', 'skip'),
   icub3d_Spell('help', 'Unravel', 'skip', 'skip'),
   icub3d_Spell('help', 'Source of Magic', 'skip', 'skip'),
   icub3d_Spell('help', 'Tip the Scales', 'skip', 'skip'),
   icub3d_Spell('help', 'Renewing Blaze', 'skip', 'skip'),
   icub3d_Spell('help', 'Fury of the Aspects', 'skip', 'skip'),
   icub3d_Spell('help', 'Stasis', 'skip', 'skip'),
   
   -- Bottom Right --
   icub3d_Spell('help', 'Temporal Anomaly', 'skip', 'skip'),
   icub3d_Talent(1),
   icub3d_Talent(2),
   icub3d_Talent(3),
   icub3d_Macro('im_trinket'),
   icub3d_Macro('im_healthstone'),
   icub3d_Skip(),
   icub3d_Spell('help', 'Blessing of the Bronze', 'skip', 'skip'),
   icub3d_Spell('help', 'Visage', 'skip', 'skip'),
   icub3d_Spell('help', 'Chosen Identity', 'skip', 'skip'),
   icub3d_Spell('help', 'Return', 'skip', 'skip'),
   icub3d_Spell('help', 'Mass Return', 'skip', 'skip'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('both', 'Living Flame', 'skip', 'skip'),
   icub3d_Spell('harm', 'Azure Strike', 'skip', 'skip'),
   icub3d_Spell('help', 'Reversion', 'skip', 'skip'),
   icub3d_Spell('harm', 'Disintegrate', 'skip', 'skip'),
   icub3d_Spell('harm', 'Fire Breath', 'skip', 'skip'),
   icub3d_Spell('help', 'Spiritbloom', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Breath', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Flight', 'skip', 'skip'),
   icub3d_Spell('help', 'Echo', 'skip', 'skip'),
   icub3d_Spell('harm', 'Quell', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Blossom', 'skip', 'skip'),
   icub3d_Spell('help', 'Verdant Embrace', 'skip', 'skip'),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),
   icub3d_Skip(),

   icub3d_Spell('simple', 'Whirling Surge(Dragonriding)'),
   icub3d_Spell('simple', 'Surge Forward(Dragonriding)'),
   icub3d_Spell('simple', 'Skyward Ascent(Dragonriding)'),
   icub3d_Spell('simple', 'Bronze Timelock(Dragonriding)'),
   icub3d_Spell('help', 'Reversion', 'skip', 'skip'),
   icub3d_Spell('help', 'Spiritbloom', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Breath', 'skip', 'skip'),
   icub3d_Spell('mouse', 'Dream Flight', 'skip', 'skip'),
   icub3d_Spell('help', 'Echo', 'skip', 'skip'),
   icub3d_Spell('harm', 'Quell', 'skip', 'skip'),
   icub3d_Spell('help', 'Emerald Blossom', 'skip', 'skip'),
   icub3d_Spell('help', 'Verdant Embrace', 'skip', 'skip'),
}


icub3d_Evoker_Talents = {
    -- PvP --
    icub3d_Spell('harm', 'Chrono Loop'),
    icub3d_Spell('harm', 'Nullifying Shroud'),
    icub3d_Spell('harm', 'Time Stop'),
    icub3d_Spell('harm', 'Swoop Up'),
 }

 icub3d_Spells['EVOKER'] = {
   specs = {
       {
          tags = {'d', 'devastation'},
          talent = icub3d_Evoker_Talents,
          actionbar = icub3d_Evoker_Devastation_Spells,
       },
       {
          tags = {'p', 'preservation'},
          talent = icub3d_Evoker_Talents,
          actionbar = icub3d_Evoker_Preservation_Spells,
       }
   }
 }