icub3d_Spells['DRUID'] = {
    specs = {
        {
            tags = {'b', 'bal', 'balance'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Faerie Swarm'),
                    icub3d_Spell('harm', 'Cyclone'),
                    icub3d_Spell('help', 'Thorns')
                }
            },
            actionbar = {
                -- Top Left
                icub3d_Spell('harm', 'Lunar Strike'),
                icub3d_Spell('harm', 'Solar Wrath'),
                icub3d_Spell('harm', 'Sunfire'),
                icub3d_Spell('harm', 'Starfall'),
                icub3d_Spell('harm', 'Starsurge'),
                icub3d_Spell('harm', 'New Moon', 'harm', 'Fury of Elune', 'harm', 'Starsurge'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('harm', 'Stellar Flare', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),
				
                -- Top Right
                icub3d_Spell('help', 'Innervate'),
                icub3d_Spell('harm', 'Hibernate'),
                icub3d_Spell('harm', 'Soothe'),
                icub3d_Spell('help', 'Solar Beam'),
                icub3d_Spell('help', 'Wild Growth', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Swiftmend', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Rejuvenation', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_PvPTalent(1),
                icub3d_PvPTalent(2),
                icub3d_PvPTalent(3),
                icub3d_Spell('help', 'Force of Nature'),

				-- Bottom Left
                icub3d_Spell('help', 'Dash'),
                icub3d_Spell('help', 'Prowl'),
                icub3d_Spell('help', 'Rebirth'),
                icub3d_Macro('im_cloak'),
				icub3d_Macro('im_racial'),
                icub3d_Spell('help', 'Gladiator\'s Medallion'),
                icub3d_Spell('help', 'Barkskin'),
                icub3d_Spell('help', 'Celestial Alignment'),
                icub3d_Spell('help', 'Flap'),
				icub3d_Skip(),
				icub3d_Skip(),
                icub3d_Spell('simple', 'Bear Form'),

				-- Bottom Right
                icub3d_Spell('simple', 'Cat Form'),
                icub3d_Spell('simple', 'Travel Form'),
                icub3d_Spell('simple', 'Stag Form'),
                icub3d_Spell('simple', 'Moonkin Form', 'simple', 'Stag Form'),
                icub3d_Macro('im_belt'),
                icub3d_Macro('im_trinket'),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Spell('simple', 'Revive'),
                icub3d_Spell('simple', 'Charm Woodland Creature'),
                icub3d_Spell('simple', 'Flap'),

				-- We have to skip these for druid, warrior, rogue
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				
                -- Cat Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Ferocious Bite', 'harm', 'Shred'),
                icub3d_Skip(),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('harm', 'Stellar Flare', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),
                
                -- Prowl Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Ferocious Bite', 'harm', 'Shred'),
                icub3d_Skip(),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('harm', 'Stellar Flare', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Bear Form
                icub3d_Spell('harm', 'Mangle'),
                icub3d_Skip(),
                icub3d_Spell('help', 'Frenzied Regeneration', 'harm', 'Mangle'),
                icub3d_Skip(),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Growl'),
                icub3d_Spell('harm', 'Growl'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('harm', 'Stellar Flare', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Moonkin Form
                icub3d_Spell('harm', 'Lunar Strike'),
                icub3d_Spell('harm', 'Solar Wrath'),
                icub3d_Spell('harm', 'Sunfire'),
                icub3d_Spell('harm', 'Starfall'),
                icub3d_Spell('harm', 'Starsurge'),
                icub3d_Spell('harm', 'New Moon', 'harm', 'Fury of Elune', 'harm', 'Starsurge'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('harm', 'Stellar Flare', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),
            }
        },
        {
            tags = {'f', 'feral'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Rip and Tear'),
                    icub3d_Spell('harm', 'Cyclone'),
                    icub3d_Spell('help', 'Thorns')
                }
            },
            actionbar = {
                -- Top Left
                icub3d_Spell('harm', 'Lunar Strike', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Solar Wrath', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Sunfire(Solar)', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('harm', 'Starsurge', 'harm', 'Moonfire'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Top Right
                icub3d_Spell('harm', 'Feral Frenzy', 'harm', 'Rake'),
                icub3d_Spell('harm', 'Hibernate'),
                icub3d_Spell('harm', 'Soothe'),
                icub3d_Spell('harm', 'Skull Bash'),
				icub3d_Spell('help', 'Wild Growth', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Swiftmend', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Rejuvenation', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_PvPTalent(1),
                icub3d_PvPTalent(2),
                icub3d_PvPTalent(3),
                icub3d_Spell('harm', 'Primal Wrath', 'harm', 'Thrash'),

				-- Bottom Left
                icub3d_Spell('help', 'Dash'),
                icub3d_Spell('help', 'Prowl'),
                icub3d_Spell('help', 'Rebirth'),
                icub3d_Macro('im_cloak'),
				icub3d_Macro('im_racial'),
                icub3d_Spell('help', 'Gladiator\'s Medallion'),
                icub3d_Spell('help', 'Survival Instincts'),
                icub3d_Spell('help', 'Berserk'),
                icub3d_Spell('help', 'Savage Roar', 'help', 'Berserk'),
                icub3d_Spell('help', "Tiger's Fury"),
                icub3d_Spell('help', 'Stampeding Roar'),
                icub3d_Spell('simple', 'Bear Form'),

				
                -- Bottom Right
                icub3d_Spell('simple', 'Cat Form'),
                icub3d_Spell('simple', 'Travel Form'),
                icub3d_Spell('simple', 'Stag Form'),
                icub3d_Spell('simple', 'Moonkin Form', 'simple', 'Stag Form'),
                icub3d_Macro('im_belt'),
                icub3d_Macro('im_trinket'),
				icub3d_Spell('harm', 'Brutal Slash', 'harm', 'Primal Wrath', 'harm', 'Thrash'),
				icub3d_Spell('harm', 'Swipe'),
				icub3d_Skip(),
				icub3d_Spell('simple', 'Revive'),
                icub3d_Spell('simple', 'Charm Woodland Creature'),
                icub3d_Spell('simple', 'Flap'),

				-- We have to skip these for druid, warrior, rogue
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
                
                -- Cat Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake'),
                icub3d_Spell('harm', 'Ferocious Bite'),
                icub3d_Spell('harm', 'Maim', 'harm', 'Shred'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Prowl Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake'),
                icub3d_Spell('harm', 'Ferocious Bite'),
                icub3d_Spell('harm', 'Maim'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Bear Form
                icub3d_Spell('harm', 'Mangle'),
                icub3d_Skip(),
                icub3d_Spell('help', 'Frenzied Regeneration', 'harm', 'Mangle'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Growl'),
                icub3d_Spell('harm', 'Growl'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Moonkin Form
                icub3d_Spell('harm', 'Lunar Strike', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Solar Wrath', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Sunfire(Solar)', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('harm', 'Starsurge', 'harm', 'Moonfire'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Remove Corruption'),
            }
        },
        {
            tags = {'g', 'guard', 'guardian'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Demoralizing Roar'),
                    icub3d_Spell('harm', 'Overrun')
                }
            },
            actionbar = {
                -- Top Left
                icub3d_Spell('harm', 'Lunar Strike', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Solar Wrath', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Sunfire(Solar)', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('harm', 'Starsurge', 'harm', 'Moonfire'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'mouse', "Ursol's Vortex", 'help', 'Tiger Dash'),
                icub3d_Spell('harm', 'Pulverize', 'harm', 'Lunar Beam', 'harm', 'Maul'),
                icub3d_Spell('help','Incarnation: Guardian of Ursoc','harm','Pulverize','harm','Lunar Beam','harm','Maul'),
                icub3d_Spell('help', 'Remove Corruption'),

				-- Top Right
                icub3d_PvPTalent(1),
				icub3d_Spell('harm', 'Hibernate'),
                icub3d_Spell('harm', 'Soothe'),
                icub3d_Spell('harm', 'Skull Bash'),
                icub3d_Spell('harm', 'Primal Wrath', 'harm', 'Thrash'),
                icub3d_Spell('harm', 'Primal Wrath', 'harm', 'Swipe'),
                icub3d_Spell('help', 'Wild Growth', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Swiftmend', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Rejuvenation', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_PvPTalent(2),
                icub3d_PvPTalent(3),

				-- Bottom Left
                icub3d_Spell('help', 'Dash'),
                icub3d_Spell('help', 'Prowl'),
                icub3d_Spell('help', 'Rebirth'),
                icub3d_Macro('im_cloak'),
				icub3d_Macro('im_racial'),
                icub3d_Spell('help', 'Gladiator\'s Medallion'),
                icub3d_Spell('help', 'Barkskin'),
                icub3d_Spell('help', 'Ironfur'),
                icub3d_Spell('help', 'Survival Instincts'),
                icub3d_Spell('help', 'Stampeding Roar'),
                icub3d_Spell('help', 'Incapacitating Roar'),
                icub3d_Spell('simple', 'Bear Form'),

				
                -- Bottom Right
                icub3d_Spell('simple', 'Cat Form'),
                icub3d_Spell('simple', 'Travel Form'),
                icub3d_Spell('simple', 'Stag Form'),
                icub3d_Spell('simple', 'Moonkin Form', 'simple', 'Stag Form'),
                icub3d_Macro('im_belt'),
                icub3d_Macro('im_trinket'),
                icub3d_Spell('help', 'Bristling Fur', 'harm', 'Stampeding Roar'),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Spell('simple', 'Revive'),
                icub3d_Spell('simple', 'Charm Woodland Creature'),
                icub3d_Spell('simple', 'Flap'),


				-- We have to skip these for druid, warrior, rogue
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),

                -- Cat Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake','harm', 'Shred'),
                icub3d_Spell('harm', 'Ferocious Bite','harm', 'Shred'),
                icub3d_Skip(),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip','harm', 'Shred'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'mouse', "Ursol's Vortex", 'help', 'Tiger Dash'),
                icub3d_Spell('harm', 'Pulverize', 'harm', 'Lunar Beam', 'harm', 'Maul'),
                icub3d_Spell('help','Incarnation: Guardian of Ursoc','harm','Pulverize','harm','Lunar Beam','harm','Maul'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Prowl Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake'),
                icub3d_Spell('harm', 'Ferocious Bite'),
                icub3d_Skip(),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'mouse', "Ursol's Vortex", 'help', 'Tiger Dash'),
                icub3d_Spell('harm', 'Pulverize', 'harm', 'Lunar Beam', 'harm', 'Maul'),
                icub3d_Spell('help','Incarnation: Guardian of Ursoc','harm','Pulverize','harm','Lunar Beam','harm','Maul'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Bear Form
                icub3d_Spell('harm', 'Mangle'),
                icub3d_Spell('harm', 'Maul'),
                icub3d_Spell('help', 'Frenzied Regeneration', 'harm', 'Mangle'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Growl'),
                icub3d_Spell('harm', 'Growl'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'mouse', "Ursol's Vortex", 'help', 'Tiger Dash'),
                icub3d_Spell('harm', 'Pulverize', 'harm', 'Lunar Beam', 'harm', 'Maul'),
                icub3d_Spell('help','Incarnation: Guardian of Ursoc','harm','Pulverize','harm','Lunar Beam','harm','Maul'),
                icub3d_Spell('help', 'Remove Corruption'),

                -- Moonkin Form
                icub3d_Spell('harm', 'Lunar Strike', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Solar Wrath', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Sunfire(Solar)', 'harm', 'Moonfire'),
                icub3d_Spell('harm', 'Moonfire'),
                icub3d_Spell('harm', 'Starsurge', 'harm', 'Moonfire'),
                icub3d_Skip(),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'mouse', "Ursol's Vortex", 'help', 'Tiger Dash'),
                icub3d_Spell('harm', 'Pulverize', 'harm', 'Lunar Beam', 'harm', 'Maul'),
                icub3d_Spell('help','Incarnation: Guardian of Ursoc','harm','Pulverize','harm','Lunar Beam','harm','Maul'),
                icub3d_Spell('help', 'Remove Corruption'),
            }
        },
        {
            tags = {'r', 'resto', 'restoration'},
            pvp = {
                alternate = icub3d_Spell('harm', 'Moonfire'),
                spells = {
                    icub3d_Spell('harm', 'Nourish'),
                    icub3d_Spell('harm', 'Cyclone'),
                    icub3d_Spell('help', 'Thorns'),
                    icub3d_Spell('help', 'Mark of the Wild'),
                    icub3d_Spell('help', 'Overgrowth')
                }
            },
            actionbar = {
                -- Top Left
                icub3d_Spell('help', 'Rejuvenation', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_Spell('help', 'Swiftmend', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Wild Growth', 'help', 'Regrowth'),
                icub3d_Spell('help', 'Lifebloom'),
                icub3d_Spell('help', 'Cenarion Ward', 'help', 'Lifebloom'),
                icub3d_Spell('mouse', 'Efflorescence'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Tranquility'),
                icub3d_Spell('help', "Nature's Cure"),
				
                -- Top Right
                icub3d_Spell('help', 'Innervate'),
                icub3d_Spell('harm', 'Hibernate'),
                icub3d_Spell('harm', 'Soothe'),
                icub3d_Spell('mouse', "Ursol's Vortex"),
                icub3d_Spell('harm', "Moonfire"),
                icub3d_Spell('harm', 'Lunar Strike'),
                icub3d_Spell('harm', 'Solar Wrath'),
                icub3d_Spell('harm', 'Sunfire(Solar)'),
                icub3d_Spell('harm', 'Starsurge', 'harm', 'Moonfire'),
                icub3d_PvPTalent(1),
                icub3d_PvPTalent(2),
                icub3d_PvPTalent(3),

				-- Bottom Left
                icub3d_Spell('help', 'Dash'),
                icub3d_Spell('help', 'Prowl'),
                icub3d_Spell('help', 'Rebirth'),
                icub3d_Macro('im_cloak'),
				icub3d_Macro('im_racial'),
                icub3d_Spell('help', 'Gladiator\'s Medallion'),
                icub3d_Spell('help', 'Barkskin'), 
                icub3d_Spell('help', 'Ironbark'),
                icub3d_Spell('help', 'Flourish', 'help', 'Barkskin'),
                icub3d_Spell('help', 'Incarnation: Tree of Life', 'help', 'Flourish', 'help', 'Barkskin'),
				icub3d_Skip(),
                icub3d_Spell('simple', 'Bear Form'),
				
                -- Bottom Right
                icub3d_Spell('simple', 'Cat Form'),
                icub3d_Spell('simple', 'Travel Form'),
                icub3d_Spell('simple', 'Stag Form'),
                icub3d_Spell('simple', 'Moonkin Form', 'simple', 'Stag Form'),
				icub3d_Macro('im_belt'),
                icub3d_Macro('im_trinket'),
				icub3d_Skip(),
				icub3d_Skip(),
                icub3d_Spell('simple', 'Revitalize'),
				icub3d_Spell('simple', 'Revive'),
                icub3d_Spell('simple', 'Charm Woodland Creature'),
                icub3d_Spell('simple', 'Flap'),

				-- We have to skip these for druid, warrior, rogue
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),
				icub3d_Skip(),

                -- Cat Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Ferocious Bite', 'harm', 'Shred'),
                icub3d_Spell('help', 'Rejuvenation'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip', 'harm', 'Shred'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Tranquility'),
                icub3d_Spell('help', "Nature's Cure"),

                -- Prowl Form
                icub3d_Spell('harm', 'Shred'),
                icub3d_Spell('harm', 'Rake', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Ferocious Bite', 'harm', 'Shred'),
                icub3d_Spell('help', 'Rejuvenation'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Shred'),
                icub3d_Spell('harm', 'Rip', 'harm', 'Shred'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Tranquility'),
                icub3d_Spell('help', "Nature's Cure"),

                -- Bear Form
                icub3d_Spell('harm', 'Mangle'),
                icub3d_Spell('help', 'Ironfur'),
                icub3d_Spell('help', 'Frenzied Regeneration', 'harm', 'Mangle'),
                icub3d_Spell('help', 'Rejuvenation'),
                icub3d_Spell('mouse', 'Thrash', 'mouse', 'Swipe', 'mouse', 'harm', 'Growl'),
                icub3d_Spell('harm', 'Growl'),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Tranquility'),
                icub3d_Spell('help', "Nature's Cure"),

                -- Moonkin Form
                icub3d_Spell('harm', 'Lunar Strike'),
                icub3d_Spell('harm', 'Solar Wrath'),
                icub3d_Spell('harm', 'Sunfire(Solar)'),
                icub3d_Spell('help', 'Rejuvenation'),
                icub3d_Spell('harm', 'Starsurge'),
                icub3d_Skip(),
                icub3d_Spell('help', 'Regrowth'),
                icub3d_Spell('harm', 'Typhoon', 'harm', 'Mass Entanglement', 'harm', 'Mighty Bash'),
                icub3d_Spell('harm', 'Entangling Roots'),
                icub3d_Spell('mouse', 'Wild Charge', 'help', 'Renewal', 'help', 'Tiger Dash'),
                icub3d_Spell('help', 'Tranquility'),
                icub3d_Spell('help', "Nature's Cure"),
            }
        }
    }
}
